### ISSUE TITLE
Support for --help argument used by Sonarr

### ISSUE THREAD

**Issue by arette** [racklin/simple-synoindex-server#2]
First, thank you for this great tool.  I'm using it for various docker containers and it's working flawlessly with one exception:

When adding the synoindex notification to Sonarr, it tests the connection by calling it with the '--help' option which causes a panic (see details below).  I also confirmed this at the command line - it appears that simple-synoindex panics when presented with '--help' or '-h' whereas /usr/syno/bin/synoindex presents the usage.  How hard would it be to fix this panic condition by at least responding to these options with something/anything valid so that it can be used in Sonarr?

Component   Message Time
NzbDroneErrorPipeline   Invalid request Validation failed: 
 -- Not a Synology or synoindex not available   12:02pm
SynologyIndexerProxy    synoindex not available: synoindex returned an error: 08/31/2016 16:02:08 - Error - panic: Get http://172.17.0.1:32699/synoindex?args=--help: EOF 08/31/2016 16:02:08 - Error - goroutine 1 [running]: 08/31/2016 16:02:08 - Error - panic(0x77d3a0, 0xc8200c80c0) 08/31/2016 16:02:08 - Error - /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6 08/31/2016 16:02:08 - Error - main.main() 08/31/2016 16:02:08 - Error - /Users/rack/workspace/golang/src/github.com/racklin/simple-synoindex-server/simple-synoindex-client.go:35 +0x694    12:02pm
synoindex   /Users/rack/workspace/golang/src/github.com/racklin/simple-synoindex-server/simple-synoindex-client.go:35 +0x694    12:02pm
synoindex   main.main() 12:02pm
synoindex   /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6  12:02pm
synoindex   panic(0x77d3a0, 0xc8200c80c0)   12:02pm
synoindex   goroutine 1 [running]:  12:02pm
synoindex   panic: Get http://172.17.0.1:32699/synoindex?args=--help: EOF   12:02pm

**Comment by racklin** [comment]
@arette thanks reporting this issue, i will trying to reproduce this issue on my computer and fixes it ASAP.

**Comment by racklin** [comment]
@arette Just update to you that this issue has been fixed in v0.3.

You can download it at https://github.com/racklin/simple-synoindex-server/releases/tag/v0.3

Thanks.

**Comment by arette** [comment]
Great job - thanks again @racklin !
