### ISSUE TITLE
Small suggestion for the Task Scheduler script

### ISSUE THREAD

**Issue by FHeilmann** [racklin/simple-synoindex-server#6]
On my synology, the suggested Task Scheduler boot-up script doesn't work, since it is executed before docker is up, causing the bind address of the server to be unavailable.

I have added a sleep before the actual execution of the server to fix this.

i.e. define another task with
`sleep(60)`
as pre-task or change the task of the synoindex server to
`sleep(60) && /volume1/homes/admin/simple-synoindex-server/synoindex-server &`

**Comment by arette** [comment]
this fix documented here first:  https://github.com/racklin/simple-synoindex-server/issues/3#issuecomment-297847630

**Comment by eltiel** [comment]
Not sure why, but after the latest DSM update the syntax for sleep has changed. 

`sleep 60` instead
